version: "{branch}-{build}"
test: off

os:
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
#  - Debug
#  - Release
  - RelWithDebInfo

init:
  - if %platform%==x64 (set CMAKE_PREFIX_PATH=C:\Qt\5.7\msvc2015_64) else (set CMAKE_PREFIX_PATH=C:\Qt\5.7\msvc2015)
  - if %platform%==x64 (set generator=Visual Studio 14 2015 Win64) else (set generator=Visual Studio 14 2015)
  - if %platform%==x64 (set msplatform=x64) else (set msplatform=Win32)
  - echo "Platform      = %platform%"
  - echo "MS Platform   = %msplatform%"
  - echo "Configuration = %configuration%"

before_build:
  - md build
  - cd build

build_script:
  - if %platform%==x64 (appveyor DownloadFile https://github.com/comphack/external/releases/download/external-25/Win64OpenSSL-1_1_1c.msi -FileName WinOpenSSL.msi) else (appveyor DownloadFile https://github.com/comphack/external/releases/download/external-25/Win32OpenSSL-1_1_1c.msi -FileName WinOpenSSL.msi)
  - start /wait msiexec /i WinOpenSSL.msi /qn
  - cmake -DCMAKE_INSTALL_PREFIX="%appveyor_build_folder%\build\install" -DCMAKE_CUSTOM_CONFIGURATION_TYPES="%configuration%" -DUSE_SYSTEM_OPENSSL=ON -G"%generator%" ..
  - cmake --build . --config %configuration% --target package

artifacts:
  - path: build\external-*.zip
    name: external_installer

deploy:
  release: external-$(appveyor_build_number)
  description: 'Development Build'
  provider: GitHub
  auth_token:
    secure: /xJRd5oxBbWa7IDdzPFbollIUAc7uqashBu8crIATrv4iUJX//DvzrGSFCaDdFsj
  artifact: external_installer
  draft: false
  prerelease: true
  on:
    branch: develop
    configuration: RelWithDebInfo
#    configuration: Release

skip_tags: true
